import os
import re
import json
import hashlib
import datetime
import urllib.request

# ===============================
# RTS AI RADAR CONFIG
# ===============================

SEARCH_TERMS = [
    "chatgpt broken",
    "chatgpt bug",
    "claude bug",
    "claude context lost",
    "cursor ai error",
    "gpt regression",
    "ai memory reset",
    "ai hallucination worse"
]

TARGETS_PATH = "radar/targets.txt"
SEEN_PATH = "radar/seen.json"
RADAR_LOG_PATH = "logs/RADAR_LOG.md"
INC_DIR = "incidents"

# ===============================
# UTIL
# ===============================

def ensure_dirs():
    os.makedirs("radar", exist_ok=True)
    os.makedirs("logs", exist_ok=True)
    os.makedirs(INC_DIR, exist_ok=True)

def now_jst():
    return (
        datetime.datetime.utcnow()
        + datetime.timedelta(hours=9)
    ).strftime("%Y%m%d_%H%M")

def sha(s):
    return hashlib.sha256(
        s.encode("utf-8")
    ).hexdigest()[:12]


def load_seen():

    if os.path.exists(SEEN_PATH):

        with open(SEEN_PATH,"r",encoding="utf-8") as f:
            return json.load(f)

    return {"seen":[]}


def save_seen(data):

    with open(SEEN_PATH,"w",encoding="utf-8") as f:

        json.dump(
            data,
            f,
            ensure_ascii=False,
            indent=2
        )

def append_log(lines):

    with open(RADAR_LOG_PATH,"a",encoding="utf-8") as f:

        f.write("\n".join(lines)+"\n")


# ===============================
# FETCH
# ===============================

def fetch_text(url):

    proxy = "https://r.jina.ai/http://" + url.replace(
        "https://",""
    ).replace(
        "http://",""
    )

    req = urllib.request.Request(
        proxy,
        headers={"User-Agent":"Mozilla/5.0"}
    )

    with urllib.request.urlopen(
        req,
        timeout=30
    ) as r:

        return r.read().decode(
            "utf-8",
            errors="ignore"
        )


def normalize(s):

    return re.sub(
        r"\s+",
        " ",
        s
    ).strip()


def extract_snippet(text):

    lines = [
        normalize(x)
        for x in text.splitlines()
        if normalize(x)
    ]

    long_lines = [
        x for x in lines
        if len(x)>=80
    ]

    if long_lines:

        return long_lines[0][:600]

    if lines:

        return lines[0][:300]

    return ""


# ===============================
# CLASSIFY
# ===============================

def classify(url,snippet):

    s = (url+" "+snippet).lower()

    if "cursor" in s:

        return "Cursor"

    if "claude" in s:

        return "Claude"

    if "chatgpt" in s or "gpt" in s:

        return "ChatGPT"

    return "Other"


def should_incident(snippet):

    keys = [

        "broken",
        "bug",
        "error",
        "downtime",
        "regression",
        "memory",
        "reset",
        "context",
        "worse",
        "unstable"

    ]

    s = snippet.lower()

    return any(k in s for k in keys)


# ===============================
# INCIDENT
# ===============================

def make_incident(url,snippet):

    ts = now_jst()

    system = classify(
        url,
        snippet
    )

    iid = f"INC_{ts}_{system}_RadarHit"

    path = os.path.join(
        INC_DIR,
        iid+".md"
    )

    body = f"""# RTS INCIDENT REPORT

Incident ID : {iid}
System : {system}
Status : OPEN

## Symptom
{snippet}

## Source
{url}

Generated by RTS Radar.
"""

    with open(
        path,
        "w",
        encoding="utf-8"
    ) as f:

        f.write(body)

    return iid


# ===============================
# MAIN
# ===============================

def main():

    ensure_dirs()

    seen = load_seen()

    hits = []

    if not os.path.exists(TARGETS_PATH):

        print("targets.txt missing")

        return

    with open(
        TARGETS_PATH,
        "r",
        encoding="utf-8"
    ) as f:

        urls = [
            x.strip()
            for x in f.readlines()
            if x.strip()
        ]


    for url in urls:

        try:

            text = fetch_text(url)

            snippet = extract_snippet(text)

            h = sha(snippet)

            if h in seen["seen"]:

                continue

            seen["seen"].append(h)

            append_log([

                f"## {now_jst()}",
                url,
                snippet,
                ""

            ])

            if should_incident(snippet):

                iid = make_incident(
                    url,
                    snippet
                )

                hits.append(iid)

        except Exception as e:

            print("error",url,e)


    save_seen(seen)

    print("Radar done",hits)


if __name__ == "__main__":

    main()
