name: Incident Report
description: RTS Incident submission
title: "[INCIDENT] "
labels: ["incident"]

body:

- type: textarea
  id: summary
  attributes:
    label: What Happened
    description: Describe the incident.
  validations:
    required: true

- type: dropdown
  id: severity
  attributes:
    label: Severity
    options:
      - S0 Catastrophic systemic failure
      - S1 Production blocking
      - S2 Degradation
      - S3 Minor
      - S4 Cosmetic
