from __future__ import annotations

import re
import hashlib

from dataclasses import dataclass
from datetime import datetime, timezone, timedelta

from pathlib import Path
from typing import List, Dict


ROOT = Path(__file__).resolve().parents[1]

LOGS_DIR = ROOT / "logs"
INCIDENTS_DIR = ROOT / "incidents"

OUTPUT = ROOT / "analyze" / "index.md"


RISK_KEYWORDS = {

"failure":["failure","failed","collapse"],

"error":["error","exception"],

"server error":["internal server error","500"],

"workflow interruption":[
"workflow interruption",
"workflow broken"
],

"token":["token expired"],

"auth":["auth failed"]
}


@dataclass
class Doc:

    file_path:Path
    rel_path:str
    content:str
    mtime:datetime

    def sha8(self)->str:

        h=hashlib.sha256(
            self.content.encode()
        ).hexdigest()

        return h[:8]


def read_text_safe(p:Path)->str:

    return p.read_text(
        encoding="utf-8",
        errors="ignore"
    )


def utc_dt_from_ts(ts:float):

    return datetime.fromtimestamp(
        ts,
        tz=timezone.utc
    )


def load_docs(folder:Path)->List[Doc]:

    docs=[]

    if not folder.exists():

        return docs

    for f in sorted(folder.glob("*.md")):

        try:

            content=read_text_safe(f)

            docs.append(

                Doc(
                    f,
                    str(f.relative_to(ROOT)),
                    content,
                    utc_dt_from_ts(
                        f.stat().st_mtime
                    )
                )
            )

        except Exception:

            continue

    return docs


def normalize_title(s:str)->str:

    s=s.strip().lower()

    s=re.sub(r"\s+"," ",s)

    return s[:120]


def extract_doc_title(content:str,fallback:str):

    for line in content.splitlines():

        if line.strip().startswith("# "):

            t=line.strip()[2:].strip()

            if t:

                return t

    for line in content.splitlines():

        if line.strip():

            return line.strip()[:120]

    return fallback


def dedup_docs_by_fingerprint(docs):

    seen={}

    for d in docs:

        title=extract_doc_title(
            d.content,
            "unknown"
        )

        fp=hashlib.sha256(

            normalize_title(title).encode()

        ).hexdigest()

        if fp not in seen:

            seen[fp]=d

    return list(seen.values())


def evidence_hits(docs,keywords):

    hits={}

    for topic,words in keywords.items():

        topic_hits=[]

        for d in docs:

            lower=d.content.lower()

            for w in words:

                if w in lower:

                    topic_hits.append(

                        f"{d.rel_path}#{d.sha8()}"

                    )

                    break

            if len(topic_hits)>=3:

                break

        hits[topic]=topic_hits

    return hits


def main():

    incidents=load_docs(
        INCIDENTS_DIR
    )

    logs_all=load_docs(
        LOGS_DIR
    )

    incidents=dedup_docs_by_fingerprint(
        incidents
    )

    combined_docs=incidents+logs_all

    risk_counts={}

    for topic,words in RISK_KEYWORDS.items():

        count=0

        for d in combined_docs:

            lower=d.content.lower()

            for w in words:

                count+=lower.count(w)

        risk_counts[topic]=count


    evidence=evidence_hits(

        combined_docs,
        RISK_KEYWORDS

    )

    now=datetime.now(
        timezone.utc
    )

    OUTPUT.parent.mkdir(

        exist_ok=True,
        parents=True

    )

    report=[]

    report.append("# RTS Sentinel Analyze")
    report.append("")
    report.append(

        f"Generated: {now.strftime('%Y-%m-%d %H:%M UTC')}"

    )

    report.append("")

    report.append("## Incident Trend")

    report.append(
        f"- incidents observed: {len(incidents)}"
    )

    if incidents:

        latest=max(
            i.mtime for i in incidents
        )

        report.append(

            f"- latest incident: {latest.strftime('%Y-%m-%d %H:%M UTC')}"

        )

    report.append("")

    report.append("## Risk Topic Ranking")

    report.append("")

    for k,v in sorted(

        risk_counts.items(),
        key=lambda x:-x[1]

    ):

        report.append(

            f"- {k}: {v}"

        )

    report.append("")

    report.append("## Evidence Hits")

    report.append("")

    for k,v in evidence.items():

        report.append(f"{k}:")

        if not v:

            report.append("- none")

        for link in v:

            report.append(

                f"- {link}"

            )

        report.append("")

    report.append("## Provenance")

    report.append("")

    report.append(

        "- Generated by scripts/analyze.py"

    )

    OUTPUT.write_text(

        "\n".join(report),

        encoding="utf-8"

    )

    badge=ROOT/"SENTINEL_STATUS.md"

    badge.write_text(

        f"RTS Sentinel ACTIVE\n{now.isoformat()}"

    )


if __name__=="__main__":

    main()
